filesize_format = "B" # can be b, kb, kib, mb, mib, gb, gib, etc
skip_welcome_message = true
disable_table_indexes = false
nonzero_exit_errors = true
startup = [
    #shell aliases BEGIN
    "alias ee = exit",
    "alias l = ls",
    "alias d = dotnet",
    "alias r = cd ~/repositories/",
    "alias sc = cd ~/sourcecode/",
    "alias nc = cd ~/AppData/Roaming/nushell/nu/config/",
    "def ex [] {explorer}",
    #shell aliases END

    #git aliases BEGIN
    "alias g = git",
    "def gl [] {git log --pretty=%h»¦«%s»¦«%aN»¦«%aE»¦«%aD -n 5 | lines | split column »¦« hash message user email date}",
    #git aliases END

    #other aliases BEGIN
    "def nudown [] {fetch https://api.github.com/repos/nushell/nushell/releases | get assets | select name download_count}",
    "def nuver [] {version | pivot key value}",
    #other aliases BEGIN
    ]
table_mode = "other" # basic, compact, compact_double, light, thin, with_love, rounded, reinforced, heavy, none, other
plugin_dirs = ["D:\\Src\\GitHub\\nu-plugin-lib\\samples\\Nu.Plugin.Len\\bin\\Debug\\netcoreapp3.1"]
pivot_mode = "auto" # auto, always, never
ctrlc_exit = false
complete_from_path = true
rm_always_trash = true
prompt = "echo $(ansi gb) $(pwd) $(ansi reset) \"(\" $(ansi cb) $(do -i { git rev-parse --abbrev-ref HEAD | str trim }) $(ansi reset) \")\" $(char newline) $(ansi yb) $(date --format \"%m/%d/%Y %I:%M:%S%.3f %p\" --raw) $(ansi reset) \"> \" | str collect"

[color_config]
#primitive_int = "green"
#primitive_decimal = "red"
#primitive_filesize = "ur"
#primitive_string = "pb"
#primitive_line = "yellow"
#primitive_columnpath = "cyan"
#primitive_pattern = "white"
#primitive_boolean = "green"
#primitive_date = "ru"
#primitive_duration = "blue"
#primitive_range = "purple"
#primitive_path = "yellow"
#primitive_binary = "cyan"
#separator_color = "purple"
#header_align = "l" # left|l, right|r, center|c
#header_color = "c" # green|g, red|r, blue|u, black|b, yellow|y, purple|p, cyan|c, white|w
#header_bold = true
#index_color = "rd"
#leading_trailing_space_bg = "white"

[line_editor]
max_history_size = 100000
history_duplicates = "ignoreconsecutive" # alwaysadd,ignoreconsecutive
history_ignore_space = false
completion_type = "circular" # circular, list, fuzzy
completion_prompt_limit = 100
keyseq_timeout_ms = 500 # ms
edit_mode = "emacs" # vi, emacs
auto_add_history = true
bell_style = "audible" # audible, none, visible
color_mode = "enabled" # enabled, forced, disabled
tab_stop = 4

[textview]
term_width = "default" # "default" or a number
tab_width = 4
colored_output = true
true_color = true
header = true
line_numbers = true
grid = false
vcs_modification_markers = true
snip = true
wrapping_mode = "NoWrapping" # Character, NoWrapping
use_italics = true
paging_mode = "QuitIfOneScreen" # Always, QuitIfOneScreen, Never
pager = "less"
#theme = "TwoDark"

# These are from a Windows system, Mac and Linux will look slightly different
path = [
    "C:\\WINDOWS\\system32",
    "C:\\WINDOWS",
    "C:\\WINDOWS\\System32\\OpenSSH\\",
]

# Some environment variables removed to protect the innocent
# These are from a Windows environemnt, Mac and Linux will look slightly different
[env]
ALLUSERSPROFILE = "C:\\ProgramData"
CommonProgramFiles = "C:\\Program Files\\Common Files"
"CommonProgramFiles(x86)" = "C:\\Program Files (x86)\\Common Files"
CommonProgramW6432 = "C:\\Program Files\\Common Files"
ComSpec = "C:\\WINDOWS\\system32\\cmd.exe"
DriverData = "C:\\Windows\\System32\\Drivers\\DriverData"
HOMEDRIVE = "C:"
NUMBER_OF_PROCESSORS = "16"
NVIDIAWHITELISTED = "0x01"
OS = "Windows_NT"
PATHEXT = ".COM;.EXE;.BAT;.CMD;.VBS;.VBE;.JS;.JSE;.WSF;.WSH;.MSC"
POWERSHELL_DISTRIBUTION_CHANNEL = "MSI:Windows 10 Pro"
PROCESSOR_ARCHITECTURE = "AMD64"
PROCESSOR_IDENTIFIER = "Intel64 Family 6 Model 158 Stepping 13, GenuineIntel"
PROCESSOR_LEVEL = "6"
PROCESSOR_REVISION = "9e0d"
ProgramData = "C:\\ProgramData"
ProgramFiles = "C:\\Program Files"
"ProgramFiles(x86)" = "C:\\Program Files (x86)"
ProgramW6432 = "C:\\Program Files"
PSModulePath = "C:\\Program Files\\WindowsPowerShell\\Modules;C:\\WINDOWS\\system32\\WindowsPowerShell\\v1.0\\Modules"
PUBLIC = "C:\\Users\\Public"
SHIM_MCCOMPAT = "0x810000001"
SystemDrive = "C:"
SystemRoot = "C:\\WINDOWS"
windir = "C:\\WINDOWS"
WSLENV = "WT_SESSION::WT_PROFILE_ID"